spring:
  h2:
    console:
      enabled: true
      path: /h2-console2
  datasource:
    url: jdbc:h2:~/local2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true